String cannot be converted to char c1.chanDirec("n"); ,error removed
error: incompatible types: String cannot be converted to char
		c1.chanDirec("n");
c1.chanDirec('n');// error removed